FROM node:22-alpine3.20


WORKDIR /app
COPY package.json  ./
COPY tsconfig.json ./ 
COPY .nmprc ./ 
COPY src ./src 
RUN ls -a 
RUN npm install && npm install -g nodemon 

EXPOSE 4001 

CMD [ "npm", "run", "dev" ]